### ISSUE TITLE
Few bugs when posting a proposal

### ISSUE THREAD

**Issue by pietrosperoni** [fairdemocracy/vilfredo-client#96] opened 2015-01-01 09:54 UTC
There was a bug:
I wrote a proposal on nightly with a title and a text. The text was not long enough. So the submit button was greyed. But I did not know why it was greyed (it does not say how much more you need to write or what the problem is) so I clicked back on the title, and now the submit button was ungreyed.

So I submit it. Nothing seemed to happen (but the proposal was actually recorded).
SO I submitted again. Same thing.
Then I went back to the proposal text and added some text, until it went over the limit and the char count was in blue. So I submitted again and it went out of the window and showed that I posted 3 empty proposal. I reloaded the page and the 3 proposal showed with the text inside and the image you can see here:

![screen shot 2015-01-01 at 10 50 36](https://cloud.githubusercontent.com/assets/1333674/5591959/14e4a7b6-91a4-11e4-92e0-74f1e0723705.png)

This leads to a number of bugs:
1) should not be possible to post twice the exact same proposal with the same title OR the same content
2) if a proposal does not have enough characters to be submitted this should still be the case even if we are editing the title.
3) if we submit a proposal when editing the text or when editing the content it should work in the same way
4) we must explain to people why a proposal is not accepted. So if they can only write so many proposal it is really confusing if you do not know what is missing. We need to accept that they might fill that in with random character, but hey, in case their proposal will have less probabilities to be accepted.

CC @derekpa @giovanisp

**Comment by giovanisp** [comment] 2015-01-01 16:02
IMHO we need to abandon the modal box and have a URL nightly.vilfredo.org/decisions/create

It should e a page template. Preparing for the html5 aside bar. We also need to confirm if "questions" is the right naming or if it is "decisions/issues/arguments..." remember that each answer (we also call them proposals.....) have questions and answers so we need to get rid of any ambiguity. 




Inviato da Tablet Samsung.


-------- Messaggio originale --------
Da: Pietro Speroni <notifications@github.com> 
Data: 01/01/2015  10:54  (GMT+01:00) 
A: fairdemocracy/vilfredo-client <vilfredo-client@noreply.github.com> 
Cc: Giovani Spagnolo <giovani@webyes.com.br> 
Oggetto: [vilfredo-client] Few bugs when posting a proposal (#96) 

There was a bug:
I wrote a proposal on nightly with a title and a text. The text was not long enough. So the submit button was greyed. But I did not know why it was greyed (it does not say how much more you need to write or what the problem is) so I clicked back on the title, and now the submit button was ungreyed.

So I submit it. Nothing seemed to happen (but the proposal was actually recorded).
SO I submitted again. Same thing.
Then I went back to the proposal text and added some text, until it went over the limit and the char count was in blue. So I submitted again and it went out of the window and showed that I posted 3 empty proposal. I reloaded the page and the 3 proposal showed with the text inside and the image you can see here:



This leads to a number of bugs:
1) should not be possible to post twice the exact same proposal with the same title OR the same content
2) if a proposal does not have enough characters to be submitted this should still be the case even if we are editing the title.
3) if we submit a proposal when editing the text or when editing the content it should work in the same way
4) we must explain to people why a proposal is not accepted. So if they can only write so many proposal it is really confusing if you do not know what is missing. We need to accept that they might fill that in with random character, but hey, in case their proposal will have less probabilities to be accepted.

CC @derekpa @giovanisp

**Comment by derekpa** [comment] 2015-01-01 18:42
OK, first you need to say where this happened. I'm guessing on nightly. I found this bug too just now and have just fixed it. The error relates to new colour coding of the proposal boxes.

**Comment by pietrosperoni** [comment] 2015-01-02 10:41
Ok, I am testing it now

**Comment by pietrosperoni** [comment] 2015-01-02 13:06
Ok cannot test it because of #99. Putting it on hold

**Comment by giovanisp** [comment] 2015-01-14 09:49
any feedbacks on my above suggestions?

**Comment by pietrosperoni** [comment] 2015-01-14 10:49
I didn't understand it :-(
Can we skype when you have time and you explain it to me? :-)

**Comment by giovanisp** [comment] 2015-01-15 10:37
Ok let's move to the next release since we wont' make it for next week.

**Comment by derekpa** [comment] 2015-04-22 15:04
This should all be fixed now.

**Closed** 2015-06-13 09:54 UTC
Labels: bug, needs review, on hold
